// <auto-generated />
using CourseApiDomain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseApiDomain.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260328202716_CategoriesUpdated")]
    partial class CategoriesUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AuthorCourse", b =>
                {
                    b.Property<int>("AuthorsAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BooksCourseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsAuthorId", "BooksCourseId");

                    b.HasIndex("BooksCourseId");

                    b.ToTable("AuthorCourse");
                });

            modelBuilder.Entity("CategoryCourse", b =>
                {
                    b.Property<int>("CategoriesCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesCategoryId", "CoursesCourseId");

                    b.HasIndex("CoursesCourseId");

                    b.ToTable("CategoryCourse");
                });

            modelBuilder.Entity("CourseApiDomain.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 4,
                            Name = "John Doe"
                        });
                });

            modelBuilder.Entity("CourseApiDomain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 5,
                            Name = "Backend"
                        });
                });

            modelBuilder.Entity("CourseApiDomain.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("CourseRating")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 5,
                            CourseName = "AspNet Core",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("CourseApiDomain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ReviewRating")
                        .HasColumnType("REAL");

                    b.Property<string>("ReviewText")
                        .HasColumnType("TEXT");

                    b.HasKey("ReviewId");

                    b.HasIndex("CourseId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            CourseId = 5,
                            ReviewRating = 10.0,
                            ReviewText = "Great course!"
                        });
                });

            modelBuilder.Entity("AuthorCourse", b =>
                {
                    b.HasOne("CourseApiDomain.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseApiDomain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("BooksCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryCourse", b =>
                {
                    b.HasOne("CourseApiDomain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseApiDomain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseApiDomain.Entities.Course", b =>
                {
                    b.OwnsOne("CourseApiDomain.Entities.CourseDetails", "CourseDetails", b1 =>
                        {
                            b1.Property<int>("CourseId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CourseDescription")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CoursePrice")
                                .HasColumnType("TEXT");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");

                            b1.HasData(
                                new
                                {
                                    CourseId = 5,
                                    CourseDescription = "AspNetCore essentials",
                                    CoursePrice = 1000.0m
                                });
                        });

                    b.Navigation("CourseDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("CourseApiDomain.Entities.Review", b =>
                {
                    b.HasOne("CourseApiDomain.Entities.Course", null)
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseApiDomain.Entities.Course", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
